name = "pavle-telegram-webhook"
main = "worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "pavle-telegram-webhook"
route = { pattern = "bot.yourbow.workers.dev/webhook", zone_name = "yourbow.workers.dev" }
